name: Java CI

on:
  push:
#    branches:
#      - main
#      - dev
  pull_request:
  workflow_dispatch: # allows us to manually run the actions

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create lib directory
        run: mkdir -p lib

      - name: Download JUnit Dependencies
        run: |
          wget -P lib/ https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.2/junit-platform-console-standalone-1.9.2.jar

      - name: Compile
        run: |
          javac -d bin --release 21 -cp "lib/*:src" $(find src -name "*.java")
          javac -d bin --release 21 -cp "bin:lib/*" $(find tests -name "*.java")

      - name: Run tests
        run: |
          mkdir -p test-results
          java -jar lib/junit-platform-console-standalone-1.9.2.jar \
               --class-path bin \
               --scan-class-path \
               --include-classname=.*Test \
               --reports-dir=test-results \
               --xml-reports-dir=test-results

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JUnit Tests           # Name of the check run which will be created
          path: test-results/*.xml    # Path to test results
          reporter: java-junit        # Format of test results
          fail-on-error: true
