name: Java CI

on:
  push:
    #    branches:
    #      - main
    #      - dev

  pull_request:
  workflow_dispatch: # allows us to manually run the actions

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create directories
        run: |
          mkdir -p lib
          mkdir -p bin
          mkdir -p test-results
          mkdir -p coverage-reports

      - name: Download dependencies
        run: |
          wget -P lib/ https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.2/junit-platform-console-standalone-1.9.2.jar
          wget -P lib/ https://repo1.maven.org/maven2/org/jacoco/org.jacoco.cli/0.8.11/org.jacoco.cli-0.8.11-nodeps.jar
          wget -P lib/ https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar

      - name: Compile source files
        run: |
          javac -d bin \
                --release 21 \
                --enable-preview \
                -cp "lib/*:src" \
                $(find src -name "*.java")

      - name: Compile test files
        run: |
          javac -d bin \
                --release 21 \
                --enable-preview \
                -cp "bin:lib/*" \
                $(find tests -name "*.java")

      - name: Run tests with coverage
        run: |
          java --enable-preview \
               -javaagent:lib/org.jacoco.agent-0.8.11-runtime.jar=destfile=coverage-reports/jacoco.exec \
               -jar lib/junit-platform-console-standalone-1.9.2.jar \
               --class-path bin \
               --scan-class-path \
               --include-classname=.*Test \
               --reports-dir test-results

      - name: Generate coverage report
        run: |
          java -jar lib/org.jacoco.cli-0.8.11-nodeps.jar report coverage-reports/jacoco.exec \
               --classfiles bin \
               --sourcefiles src \
               --html coverage-reports/html \
               --xml coverage-reports/coverage.xml

      - name: Parse JaCoCo Report
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');

            // Ruta del archivo XML generado por JaCoCo
            const jacocoFilePath = 'coverage-reports/coverage.xml';

            // Inicializar variables para almacenar los resultados
            let coveragePercentage = 'N/A', totalLines = 0, coveredLines = 0, missedLines = 0;

            // Verificar si el archivo existe
            if (fs.existsSync(jacocoFilePath)) {
              console.log("JaCoCo report found. Parsing...");

              // Leer el contenido del archivo
              const jacocoData = fs.readFileSync(jacocoFilePath, 'utf-8');
              console.log("JaCoCo Report Content:", jacocoData); // Imprimir contenido del archivo para depuración

              // Buscar el nodo <counter type="LINE">
              const lineCoverageMatch = jacocoData.match(/<counter type="LINE" missed="(\d+)" covered="(\d+)"\/>/);
              if (lineCoverageMatch) {
                // Extraer datos de las líneas no cubiertas y cubiertas
                missedLines = parseInt(lineCoverageMatch[1], 10);
                coveredLines = parseInt(lineCoverageMatch[2], 10);
                totalLines = missedLines + coveredLines;

                // Calcular el porcentaje de cobertura
                coveragePercentage = totalLines > 0 ? ((coveredLines / totalLines) * 100).toFixed(2) : '0.00';
                console.log(`Extracted JaCoCo Coverage - Missed Lines: ${missedLines}, Covered Lines: ${coveredLines}, Coverage Percentage: ${coveragePercentage}%`);
              } else {
                console.log("No <counter type=\"LINE\"> node found in JaCoCo report.");
              }
            } else {
              console.log("JaCoCo report not found.");
            }

            // Crear resumen
            const summary = `
            ### JaCoCo Code Coverage Report
            - **Line Coverage**: ${coveragePercentage}%
            - **Total Lines**: ${totalLines}
            - **Covered Lines**: ${coveredLines}
            - **Missed Lines**: ${missedLines}
            `;
            
            console.log("Generated Summary:", summary);
            
            // Añadir el resumen a la pestaña "Summary" de GitHub Actions
            core.summary.addRaw(summary).write();

